language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache/yarn"
  - node_modules
before_install:
- yarn config set no-progress
- yarn global add greenkeeper-lockfile@1
install:
- yarn
before_script: greenkeeper-lockfile-update
script: yarn test
after_script: greenkeeper-lockfile-upload
after_success: yarn codecov
deploy:
  provider: npm
  email: mlahlou@protonmail.ch
  api_key:
    secure: BBAzKU6rnL58Rx4RqqZk7wClnqeJJzBpFQf/Hd95vo3OK1vtT+gcZupRog8awReFZp6CF6AVQizfK2O+t5VfqI58N4BgWP9DTs6ZHnXUvV4u0Djlr5hDUuk0spIi6Som/kyJ0ytaeu68JUK31xZa0VJQPmyQZ11JH/LoyP8BISm84B80g8pBhOXnp1nexU+Kn2DWXMDWX6OKP+y8xcuN/NEBzIrFmPg9o/D7gN41MkJRmQ5tsCjlO2seiv7e6azZKk1JeF7KNIb8dae3Ae55vFrNggPmbYYQt30nGxXgmL0STTFkKxFsAf4glIN1Ge2z4vUsFbMJSADnnaBSiwouQVJ3o4MAyEIm66oLT+vOxkwfta3raYjytQ7oTEJBTFKGuFFpunj/tOIjv07sReWJ+9yjlplcwYafqKU2g+JzHx2Mw86pDx5u1MeVB6T2OuHKd9xcnWrZ0Tj7Wki83/YV4/qKK8tcVGGptmKkUTix+WEW3Fi+mJEA4z/jJRCDhUtuhdXFzoC0HOzPmTAQX3JwuBomhuH84Orb3QlZjsXnJ+xic/ycjppfNJL3v9MK8oHQTkGmuUKuA6QjyZc8RM9a2ZGpVHxZrLqhP8Wo6epU36tXncuOpTrkjJ27lSacGEkGrfzVf77VmdLqChwDfmXR5Nqw7sie1eHSCM9R3bhaw6I=
  on:
    tags: true
    node: '8'
  skip_cleanup: true
env:
  global:
    secure: gMX/67uE1EsO6BhHxgzzUmFd1Q0rmblgPfkYfP/3GHo53JIa6xWg4522cUVJAawzxnEdrwJ3BFAMT31okP6hTGftY0xPlFzgFmgBU/Vkkc6MRpslcbMHlsn/Gs1uAfcDZq3E4u1usLoMKKGTJeAkneyHUqzsYNxPIEUSmJbYG69l7hdRX2TrQD19/AwA9BapL21yp/gPqxexnjEK1hMgcn3rnSAoPzyGqLVdStmMQ/uKf/rBg4jincXPAPZeZC2m+OaeIfbCPg2Q1/G/ozWWz2aZUL1F1TNs1qlnJuXLQ+n2b67moJyXBEVw9CW9LRezBGmXo1z+sZlGzK76/IATVBpCc1Q/QF8Sdxoh484Al18bLaQjTVqiMl72LYYMJqskfqrm16chj4Nukg9TAodAMlCew4zl0VU7BrTA034namrzQsLooXmTq2Lv3No0TsPGxrdZ+HNTVC2JxqEK33t/+pAXG6nCi1cAa7utSefw8SukFgVHGiWYUdcbzz7K3lc+0mmGJ5Qzz/YWfu5E0hf96laUv5p+FyuwFIV1LS6Z74iDASfQrI72OeOAh7vG9l7vbO6CNCcPN6r6ul125CO26CL/0G5Tvz2iCP6Ik1QAK+INY6P2O03dx/q4RNaLkI0mCjL3uG/47VS7389mj5txPKm2ow1qWD/uVXhkW6J7aV4=
